spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_schema:
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE

logging:
  level:
    com.prueba.devsubank: debug
devsubank:
  limite-diario-retiro: 1000
  secret: secret-key-12345